"""fixBucketsNameInBoard

Revision ID: 41afe7f2e0de
Revises: 02ed98150a4d
Create Date: 2023-07-03 07:37:21.107005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41afe7f2e0de'
down_revision = '02ed98150a4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bucktes', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucktes', type_='unique')
    # ### end Alembic commands ###
