"""addTaskIdInSubstasks

Revision ID: b3dbd09f787d
Revises: 97ef70dcd9fa
Create Date: 2023-07-04 01:21:15.391526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dbd09f787d'
down_revision = '97ef70dcd9fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('task_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'subtasks', ['id'])
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.drop_constraint(None, 'subtasks', type_='unique')
    op.drop_column('subtasks', 'task_id')
    # ### end Alembic commands ###
